### ISSUE TITLE
[question] How to implement Redis to share WS messages and connections?

### ISSUE THREAD

**Issue by JulienBreux** [vaniila/hyper#2]
Hello,

Before all: Thanks a lot for your qualified work!

I have a tiny question: How to implement Redis to share WS messages and connections?

**Comment by samuelngs** [comment]
Hi @JulienBreux 

Sorry for late response, I've been busy. 
I added an example of Redis PubSub at the link below. (_Do not use it in production tho_)

https://github.com/vaniila/hyper/tree/master/examples/websocket-redis

Let me know if you have any questions :smile:

**Comment by JulienBreux** [comment]
Hi @samuelngs 

Very nice software design!

Thanks a lot!
