### ISSUE TITLE
[feature request] Interface for logger

### ISSUE THREAD

**Issue by JulienBreux** [vaniila/hyper#3]
Hello,

It's me again. Today I have a feature request for you.

---
Feature request: Have an interface for logger

Actually, I use [Zap from Uber](https://github.com/uber-go/zap) to log.
It's very useful because you can set the level and format (Info and Json in my case).

The problem with `Hyper` is that it uses the default go log package.

Can-we together create a common interface for logger in `Hyper`?

For example:

```go
type LoggerField interface {
	Key() string
	Value() interface{}
}

type Logger interface {
	Debug(msg string, fields ...LoggerField)
	Info(msg string, fields ...LoggerField)
	Warn(msg string, fields ...LoggerField)
	Error(msg string, fields ...LoggerField)
	Fatal(msg string, fields ...LoggerField)
	Panic(msg string, fields ...LoggerField)
}
```

Thank in advance to take time to read my feature request :)

**Comment by samuelngs** [comment]
@JulienBreux Thanks for your feature request. I like the idea. Let's move forward. 😃 👍

**Comment by JulienBreux** [comment]
@samuelngs do you have seen my PR #4 ?

**Comment by samuelngs** [comment]
@JulienBreux Yep I did. Things look great thanks 👍 We probably should expose the logger interface at the router context and graphql context.

**Comment by samuelngs** [comment]
Custom logger feature has been implemented and merged. Closed Issue.

Thanks @JulienBreux
